# Generated by Django 3.2 on 2023-02-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop', '0005_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(to='onshop.Product'),
        ),
    ]
