# Generated by Django 3.2 on 2023-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop', '0007_auto_20230204_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='onshop.Product'),
        ),
    ]
