# Generated by Django 3.2 on 2023-02-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onshop', '0009_auto_20230204_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onshop.product'),
            preserve_default=False,
        ),
    ]
